[package]
name = "euler"
version = "0.1.0"
authors = ["Takumi Miyazaki <coom_st@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"